// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAT6rEtGJIYEVNzJ-jKN5vxgFKTOkc-U0',
    appId: '1:351602177212:web:9cb88a97a01863b0ab4cb9',
    messagingSenderId: '351602177212',
    projectId: 'notesbycj',
    authDomain: 'notesbycj.firebaseapp.com',
    storageBucket: 'notesbycj.firebasestorage.app',
    measurementId: 'G-PDL62VESNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKUweFnpgR53jfADxvLGLhjlOad5Snt18',
    appId: '1:351602177212:android:b553126e3db70743ab4cb9',
    messagingSenderId: '351602177212',
    projectId: 'notesbycj',
    storageBucket: 'notesbycj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYsHwNUGDOaUNogobvChegPM2LoubCi60',
    appId: '1:351602177212:ios:6738b24d12efa86aab4cb9',
    messagingSenderId: '351602177212',
    projectId: 'notesbycj',
    storageBucket: 'notesbycj.firebasestorage.app',
    iosBundleId: 'com.jakhecs.notesbycj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYsHwNUGDOaUNogobvChegPM2LoubCi60',
    appId: '1:351602177212:ios:6738b24d12efa86aab4cb9',
    messagingSenderId: '351602177212',
    projectId: 'notesbycj',
    storageBucket: 'notesbycj.firebasestorage.app',
    iosBundleId: 'com.jakhecs.notesbycj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAT6rEtGJIYEVNzJ-jKN5vxgFKTOkc-U0',
    appId: '1:351602177212:web:98e76c6ca6bb8032ab4cb9',
    messagingSenderId: '351602177212',
    projectId: 'notesbycj',
    authDomain: 'notesbycj.firebaseapp.com',
    storageBucket: 'notesbycj.firebasestorage.app',
    measurementId: 'G-13S68CN14T',
  );
}
